DB課題3：問題番号001～005
ryoma-yama/quelcode-db pull request #3
Opened 2020-06-23 14:38 UTC by ryoma-yama

DB課題3：問題番号001～005の提出です。

2020-06-24 02:47 UTC, piasoratech requested changes
No001で指摘した内容は他の課題でも同じように確認・修正をしてください

2020-06-24 02:47 UTC, piasoratech commented on db/db-challenge3/db-001/db-001.sql
> +    1,
`auto_increment`の設定をしているカラムはINSERT文で明記しないのが普通です。

2020-06-24 02:47 UTC, piasoratech commented on db/db-challenge3/db-001/db-001.sql
> +  )
`;`つけましょう

2020-06-24 02:47 UTC, piasoratech commented on db/db-challenge3/db-001/db-001.sql
> +INSERT INTO users
複数レコードを１つのINSERT文で書くこともできるので調べておきましょう。
この内容に関する修正は不要です。

2020-06-24 03:52 UTC, ryoma-yama commented on db/db-challenge3/db-001/db-001.sql
> +INSERT INTO users
https://johobase.com/multiple-insert-sql/
リンク先で構文を確認しました。
`INSERT INTO $table ($column1[, ...]) VALUES ($value1[, ...])[, ( ...];`
ありがとうございます！

2020-06-24 04:40 UTC, piasoratech reviewed
No001～005についてはOKです
次の段階に進みましょう！

2020-06-24 09:40 UTC, yusaku-inamura requested changes
みました〜 🙆‍♂️ 
ちょっとだけコメントしてるので確認お願いします。

2020-06-24 09:40 UTC, yusaku-inamura commented on db/db-challenge3/db-006/db-006.sql
> +SELECT `id`,
予約語っぽいのも見当たりませんが、ここでバッククォートをつけてる理由がありますか?
カラム名などをバッククォートで囲むのは予約語になってしまっている文言をエスケープをする時であって、あまり何にでもつけるといった感じのものではないですかね。
まあつけても良いと言えば良いのですが、それよりもせっかく勉強段階なわけですしなぜつけているかをちゃんと把握して適切なタイミングで使える方が良いですね。
直さなくってもいいですが気に留めておいてください。

2020-06-24 09:40 UTC, yusaku-inamura commented on db/db-challenge3/db-007/db-007.sql
> +    ELSE '禁止'
今回対象のカラムはnull不許可であることから何かしらの値が入っているはずと考えると、ELSEだけではなく0の場合に不許可と明示的に書くべきですね。
また、条件が文字列の1となってしまっておりますが、該当のカラムがtinyintなのであれば文字列ではなく数値を条件とするべきでしょう。

2020-06-24 09:40 UTC, yusaku-inamura commented on db/db-challenge3/db-010/db-010.sql
> +ORDER BY posts.chat_id;
おしい!
このSQLだともし削除済みのユーザーが最後の投稿をしていた場合、結果行から除外されてしまいますね。
最新の投稿が削除済みだった場合はちゃんと考慮できているので、あとはその応用で同じようにできるはず!

2020-06-24 10:59 UTC, ryoma-yama commented on db/db-challenge3/db-006/db-006.sql
> +SELECT `id`,
phpMyAdminのSQL実行ツールでSELECTボタンを押すと, バッククオート付きで全列出力されるので, それをそのまま使ってました。意味を理解した上で使いたいと思います。ありがとうございます！

2020-06-25 02:53 UTC, himaru-jp commented
No6-10レビューOKです。

2020-06-25 06:37 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-25 06:37 UTC, piasoratech commented on db/db-challenge3/db-011/db-011.sql
> +  AND modify_member_id = 1;
これは要件を満たせていないです。
条件は問題文のインデントが1段下がっている部分のみで他は更新内容の要件です。

2020-06-25 06:37 UTC, piasoratech commented on db/db-challenge3/db-012/db-012.sql
> +BEGIN;
これもNo011と同じ指摘内容です。要件が満たせていません。

2020-06-25 06:37 UTC, piasoratech commented on db/db-challenge3/db-013/db-013.sql
> +SET is_deleted = 1
更新日時の更新ができていません。

2020-06-25 06:37 UTC, piasoratech commented on db/db-challenge3/db-014/db-014.sql
> +BEGIN;
SQL文自体は合っていますが、他の問題を修正することによって実行結果が変わってくると思うので、キャプチャ画像は撮り直しをしてください。

2020-06-25 08:38 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-25 08:38 UTC, piasoratech commented on db/db-challenge3/db-012/db-012.sql
> +BEGIN;
要件をまだ満たせていないです。
実行結果(SELECTで表全体を取得したもの)と要件を確認してもう一度修正してください。

2020-06-26 02:09 UTC, piasoratech approved these changes
ＯＫです！
お疲れ様でした！

2020-06-26 15:54 UTC, merged